"""initial

Revision ID: f4ff3683e355
Revises: 
Create Date: 2019-01-26 17:07:39.428722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ff3683e355'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=70), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=False),
    sa.Column('photo_url', sa.String(length=150), nullable=False),
    sa.Column('post_timestamp', sa.DateTime(), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('section_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_posts')
    # ### end Alembic commands ###
